services:
  lc0:
    restart: no
    build:
      dockerfile: ./Dockerfile
    container_name: lc0
    image: lc0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
